### ISSUE TITLE
Cannot update url on nightly

### ISSUE THREAD

**Issue by retornam** [mozilla/home-snippets-switcher#2]
Using  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:16.0) Gecko/16.0 Firefox/16.0a1 it is impossible to update snippet url. See image

http://cl.ly/2R2F2Z1f2B2U1a222847

**Comment by Osmose** [comment]
Can you try removing the addon and reinstalling the latest version? I pushed some fixes a while back (I should probably commit those, oops).

https://github.com/downloads/mozilla/home-snippets-switcher/home-snippets-switcher.xpi

**Comment by retornam** [comment]
The latest version does not work at all on nightly

**Comment by Osmose** [comment]
I've uploaded a newly built version that works on my copy of nightly, can you test to see if it works for you?

**Comment by retornam** [comment]
I tried the latest version and this is what I get in the error console

Timestamp: 6/15/12 10:30:41 AM
Error: The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must to be declared in the document or in the transfer protocol.
Source File: resource://jid0-wridmrdjmf3xffzzwnabhdnian8-at-jetpack/home-snippets-switcher/data/options.html?sample=
Line: 0

Timestamp: 6/15/12 10:31:52 AM
Error: An exception occurred.
Traceback (most recent call last):
  File "resource://jid0-wridmrdjmf3xffzzwnabhdnian8-at-jetpack/home-snippets-switcher/data/js/options.js", line 1, in 
    var Options = (function () {
  File "resource://jid0-wridmrdjmf3xffzzwnabhdnian8-at-jetpack/home-snippets-switcher/data/js/options.js", line 135, in 
    return $this.init();
  File "resource://jid0-wridmrdjmf3xffzzwnabhdnian8-at-jetpack/home-snippets-switcher/data/js/options.js", line 19, in 
    $this.presets = JSON.parse(localStorage["presets"])
SyntaxError: JSON.parse: unexpected character

**Comment by Osmose** [comment]
Confirmed on IRC that the newest download works. Apparently Github was caching the old addon file because the new one had the same filename. Silly.
